###################################################################################################
## Manual Mode
###################################################################################################
  manual_mode:
    name: Manual Mode
    icon: mdi:minus-circle

###################################################################################################
## Advanced View
###################################################################################################
  advanced_view:
    name: Advanced View
    icon: mdi:view-split-vertical