#######################################################################################################################
## Template Binary Sensors
#######################################################################################################################
  - platform: template
    sensors:
#######################################################################################################################
## Manual Mode Activated
#######################################################################################################################
      manual_mode:
        value_template: "{{ is_state('input_boolean.manual_mode', 'on') }}"

#######################################################################################################################
## Automation Disabled
## - used in lovelace for home page conditional card
#######################################################################################################################
      automation_disabled:
        value_template: "{{ states('group.automation_controls') == 'off' }}"
