#######################################################################################################################
## Delayed Automations
## - automations delayed at startup
#######################################################################################################################
  delayed_automations:
    icon: mdi:google-circles-group
    control: hidden
    all: true
    entities:
#      - group.alarm_clock_delayed_automations # we're controlling alarm clock state at restart manually
#      - group.radio_delayed_automations # we're controlling radio state at restart manually
#      - automation.alarm_clock_player_offline # media players need to come online
#      - automation.radio_player_offline # media players need to come online
#      - automation.notification_announcement_player_offline # media players need to come online
      - automation.automation_set_device_user_state # user state bools turn on when devices come online
      - automation.house_alarm_occupancy_mode_control #TEST - alarm disarming on restart
      - automation.garage_door_lights # needs garage door to be online
      - automation.light_sun_is_up # sun will trigger when it updates
      - automation.light_sun_is_down # sun will trigger when it updates
      - automation.media_player_volume_change # media players trigger when they come online
      - automation.presence_someone_arrives_home # triggers when at home sensors come online
      - automation.presence_someone_leaves_home # triggers when at home sensors come online
      - automation.schedule_auto_shift_select # needs calendar to be online
      - automation.system_sensor_unavailable_alert # needs zwave devices to be started or false triggers

#TODO can we remove some by increasing trigger for times?
#######################################################################################################################
## User State Contols
## - used to reset user state controls (away_state, manual mode)
#######################################################################################################################
  user_state_controls:
    icon: mdi:google-circles-group
    control: hidden
    all: true
    entities:
      - input_boolean.living_room_pot_lights
      - input_boolean.office_fan
      - input_boolean.upstairs_bedroom_fan
      - input_boolean.upstairs_bathroom_fan

#######################################################################################################################
## Automation Contols
## - used to show disabled automations in lovelace
#######################################################################################################################
  automation_controls:
    icon: mdi:google-circles-group
    control: hidden
    all: true
    entities:
      - input_boolean.ceiling_fan_automation
      - input_boolean.house_alarm_enabled
      - input_boolean.house_climate_automation
      - input_boolean.garage_climate_automation
      - input_boolean.garage_door_automation
      - input_boolean.light_automation
      - input_boolean.media_player_automation
      - input_boolean.notification_automation
      - input_boolean.presence_automation
      - input_boolean.schedule_automation
      - input_boolean.sensor_automation
      - input_boolean.radio_automation
      - input_boolean.system_automation
      - input_boolean.weather_automation
      - input_boolean.vent_fan_automation