#######################################################################################################################
## Null Script
## null script placeholder for service templates
#######################################################################################################################
  null_script:
    sequence: